server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/numbers_counter?currentSchema=numbers_counter
    username: root
    password: root
  flyway:
    baseline-on-migrate: true
    baseline-version: 0
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    generate-ddl: off
    hibernate:
      ddl-auto: update
    database: mysql
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yml
    default-schema: numbers_counter
